export const classes = {
    warrior: {
        classTitle: 'Warrior',
        vitality: 11,
        attunement: 8,
        endurance: 12,
        strength: 13,
        dexterity: 13,
        resistance: 11,
        intelligence: 9,
        faith: 9,
    },
    knight: {
        classTitle: 'Knight',
        vitality: 14,
        attunement: 10,
        endurance: 10,
        strength: 11,
        dexterity: 11,
        resistance: 10,
        intelligence: 9,
        faith: 11,
    },
    wanderer: {
        classTitle: 'Wanderer',
        vitality: 10,
        attunement: 11,
        endurance: 10,
        strength: 10,
        dexterity: 14,
        resistance: 12,
        intelligence: 11,
        faith: 8,
    },
    thief: {
        classTitle: 'Thief',
        vitality: 9,
        attunement: 11,
        endurance: 9,
        strength: 9,
        dexterity: 15,
        resistance: 10,
        intelligence: 12,
        faith: 11,
    },
    bandit: {
        classTitle: 'Bandit',
        vitality: 12,
        attunement: 8,
        endurance: 14,
        strength: 14,
        dexterity: 9,
        resistance: 11,
        intelligence: 8,
        faith: 10,
    },
    hunter: {
        classTitle: 'Hunter',
        vitality: 11,
        attunement: 9,
        endurance: 11,
        strength: 12,
        dexterity: 14,
        resistance: 11,
        intelligence: 9,
        faith: 9,
    },
    sorcerer: {
        classTitle: 'Sorcerer',
        vitality: 8,
        attunement: 15,
        endurance: 8,
        strength: 9,
        dexterity: 11,
        resistance: 8,
        intelligence: 15,
        faith: 8,
    },
    pyromancer: {
        classTitle: 'Pyromancer',
        vitality: 10,
        attunement: 12,
        endurance: 11,
        strength: 12,
        dexterity: 9,
        resistance: 12,
        intelligence: 10,
        faith: 8,
    },
    cleric: {
        classTitle: 'Cleric',
        vitality: 11,
        attunement: 11,
        endurance: 9,
        strength: 12,
        dexterity: 8,
        resistance: 11,
        intelligence: 8,
        faith: 14,
    },
    deprived: {
        classTitle: 'Deprived',
        vitality: 11,
        attunement: 11,
        endurance: 11,
        strength: 11,
        dexterity: 11,
        resistance: 11,
        intelligence: 11,
        faith: 11,
    },
}

export default classes